trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    inputs:
      version: '6.x'
      includePreviewVersions: true

  - script: dotnet build --configuration Release
    displayName: 'Build the games'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/games.zip'
      replaceExistingArchive: true
    displayName: 'Archive the games'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/games.zip'
      ArtifactName: 'games'
      publishLocation: 'Container'
    displayName: 'Publish artifacts'
