trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    inputs:
      version: '6.x'
      includePreviewVersions: true

  - script: dotnet build --configuration Release
    displayName: 'Build the games'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: '1a6852f1-f26f-481f-9197-70499d5d8bbb'
      appType: 'webApp'
      WebAppName: 'webappnetsite'
      packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'